name: packaging

on:
  release:
    types:
      - created

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |-
          yarn install
      - name: Package CLI
        run: |-
          ./scripts/release/tarballs
      - name: Publish Release
        run: |-
          ./scripts/release/publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
